version: '3.7'
services:
  タイトル:
    build:
      context: ./golang/
      dockerfile: Dockerfile.dev
    container_name: "タイトル"
    volumes:
      - ../:/タイトル
    ports:
      - "8080:8080"
    tty: true
